### ISSUE TITLE
Order Page: Vẫn chưa đưa phần Đường/Đá vào từng món [Website đã update rồi]

### ISSUE THREAD

**Issue by binxynh** [tuannv19/SAW#16]
![IMG_6990](https://user-images.githubusercontent.com/33717296/59026847-9694be80-8881-11e9-83b8-4cf3c2ef6f0d.PNG)

**Comment by tuannv19** [comment]
@dhhieu113  cho tên 1 item nào có mấy option trên để check đc ko ?

**Comment by truongmediastep** [comment]
http://dev.sawadee.com.vn/vi/tra-thai-xanh-sua-tuoi-77848 

detai: http://testapi.sawadee.com.vn/api/v1/products/77848

**Comment by dhhieu113** [comment]
http://dev.sawadee.com.vn/vi/tra-thai-xanh-sua-tuoi-77848

detai: http://testapi.sawadee.com.vn/api/v1/products/77848


@tuannv19
