### ISSUE TITLE
Chưa tính phí vận chuyển

### ISSUE THREAD

**Issue by binxynh** [tuannv19/SAW#17]
![IMG_6992](https://user-images.githubusercontent.com/33717296/59026884-ad3b1580-8881-11e9-9748-6e33ced5b9e1.PNG)

**Comment by tuannv19** [comment]
@dhhieu113  https://github.com/tuannv19/SAW/issues/9

**Comment by dhhieu113** [comment]
http://testapi.sawadee.com.vn/api/v1/orders/calculate-ship-fee

anh xem ở tab Order Screen nhe:
 https://docs.google.com/spreadsheets/d/1KS-nRYw5g_cvb0D1z2U26xSfDLgKdafl-F-E9hjD1fM/edit#gid=1925990921

![image](https://user-images.githubusercontent.com/19473530/59170662-e3221780-8b69-11e9-8d1e-813a7367db2f.png)
