### ISSUE TITLE
iOs [Home] - Thực đơn

### ISSUE THREAD

**Issue by binxynh** [tuannv19/SAW#24]
1. Đổi text giúp em thành:
MÓN NỔI BẬT

2. Chỉ để lại giúp em 4 nhóm sản phẩm được khoanh tròn

3. Khi click vào 1 trong 4 nhóm -> ví dụ chọn trà thái xanh, lúc mở trang đặt hàng em nghĩ nên xổ ra sẵn các món trong trà thái xanh, hiện tại nó chỉ trỏ về trang đặt hàng chứ không có xổ ra menu Trà Thái xanh
![IMG_7168](https://user-images.githubusercontent.com/33717296/59989486-92caaf80-9669-11e9-9b58-ee5a0fd4bee3.jpg)

**Comment by tuannv19** [comment]
@dhhieu113 @QuyNguyenThu

**Comment by binxynh** [comment]
Team ơi cái này 2 & 3 đã done rồi.
mục 1 em chưa thấy đổi ạ
