### ISSUE TITLE
iOs - Profile

### ISSUE THREAD

**Issue by binxynh** [tuannv19/SAW#25]
Bản update mới nhất bị lỗi:
1. Tên hiển thị có %20 

2. Mất hình đại diện đã tải lên trước đó?
![IMG_7170](https://user-images.githubusercontent.com/33717296/59989527-c86f9880-9669-11e9-8501-2cc25c40aa71.jpg)

**Comment by tuannv19** [comment]
@dhhieu113

**Comment by dhhieu113** [comment]
@tuannv19 

App gửi  tên lên có % 
![ảnh](https://user-images.githubusercontent.com/19473530/60087197-ba537200-9766-11e9-882f-1dd992690c45.png)
