### ISSUE TITLE
iOs - Đặt hàng

### ISSUE THREAD

**Issue by binxynh** [tuannv19/SAW#26]
1. Đường line của group món cho nó thành màu xám giúp em với, hiện tại nó bị chìm vào phần món luôn.

2. Click vào đúng dấu mũi tên thì mới xổ món ra => em muốn click vào vị trí nào trên line của group cũng xổ món ra được.
![IMG_7169](https://user-images.githubusercontent.com/33717296/59989604-1a182300-966a-11e9-8daa-8e99604290e0.jpg)

**Comment by tuannv19** [comment]
@binxynh  Cho anh mã màu đi .

**Comment by tuannv19** [comment]
#F1F1F1 @QuyNguyenThu

**Comment by binxynh** [comment]
Done
