### ISSUE TITLE
iOs - Lỗi đặt hàng

### ISSUE THREAD

**Issue by binxynh** [tuannv19/SAW#29]
Khi chọn thanh toán bằng Momo - mặc dù chưa hoàn thành bước thanh toán nhưng vẫn ghi nhận trong lịch sử giao dịch.

![IMG_7258](https://user-images.githubusercontent.com/33717296/60393974-45f24780-9b47-11e9-9318-8890e5d2704e.PNG)

**Comment by binxynh** [comment]
Trong hình là giao dịch số 2 & 4 (từ trên xuống, em xác nhận nhưng chưa thanh toán nhưng vẫn ghi nhận lịch sử giao dịch)

**Comment by tuannv19** [comment]
@dhhieu113 
theo lý thuyết mình call 1 lần : 
- lần 1 tạo hoá đơn 
- lần 2 update thông tin (Sau khi thanh toán )
check lại xem đúng ko hiệu

**Comment by binxynh** [comment]
@tuannv19 không phải anh nha.
Ở đây là 1 là em chọn thanh toán = Momo, không submit thanh toán
Lần 2 là em chọn thanh toán tiền mặt & đã xác nhận

**Comment by tuannv19** [comment]
> @dhhieu113
> theo lý thuyết mình call 1 lần :
> 
> * lần 1 tạo hoá đơn
> * lần 2 update thông tin (Sau khi thanh toán )
>   check lại xem đúng ko hiệu

https://docs.google.com/spreadsheets/d/1KS-nRYw5g_cvb0D1z2U26xSfDLgKdafl-F-E9hjD1fM/edit#gid=547197325

**Comment by dhhieu113** [comment]
a @tuannv19  có 1 API để thêm order vào và 1 API update tình trạng order.

nên chỗ nay anh xem gọi API lúc nào hợp lý theo ý của Loan là dc.

**Comment by tuannv19** [comment]
@dhhieu113  Ngoại trừ thanh toán = tiền mặt những đơn hàng nào ko có  gọi api "update-payment-status" thì mình ko trả về đc ko?
