### ISSUE TITLE
iOs - Bỏ cate trong mục order

### ISSUE THREAD

**Issue by binxynh** [tuannv19/SAW#30]
Anh Tuấn ẩn giúp em cái mục TOPPING trong mục order nhé. Vì topping có trong từng món rồi nè
![IMG_7259](https://user-images.githubusercontent.com/33717296/60394140-bbf7ae00-9b49-11e9-9c8f-8740b12e35f7.PNG)

**Comment by tuannv19** [comment]
@dhhieu113

**Comment by binxynh** [comment]
Cái này anh tự xử lý được mà anh @tuannv19 ơi, anh ẩn nó đi thôi.
Trên web anh Hiệu ẩn rồi: http://dev.sawadee.com.vn/vi

**Comment by tuannv19** [comment]
Nó giống ticket này https://github.com/tuannv19/SAW/issues/24 . Dữ liệu từ API trả về nên để API quản lý sau này chỉnh sửa dễ hơn.

**Comment by dhhieu113** [comment]
OK a @tuannv19  em sẽ ẩn cho anh
