### ISSUE TITLE
 API gửi fireBaseToken luôn response data: false 

### ISSUE THREAD

**Issue by tuannv19** [tuannv19/SAW#6]
Android app: Hiện tại không thể gửi FireBaseToken bằng API nên API không thể push bằng cách send token sau đó send Push được. 
 API gửi fireBaseToken luôn response data: false ({"code":0,"data":false,"validationErrors":null,"message":null,"stackTrace":null}) voi ca 2 requests sau:
{"deviceId":"e6cf1d2318b1e085","FireBaseToken":"fVuFWIjEfX0:APA91bHmE4POcCZtzRnROYGAuCEoKrK_Ayv2U9Ptfz3jA4OEEbXOBURsWOf8JWC8ghjrpx2seWmxLcYjUNxnYl0FERt9SiGuE8QwQ-xoZ2m1K9dA8Ii4NdEPTAwbuspF3-YmgSCUmFZg","os":"android"} hay
{"deviceId":"e6cf1d2318b1e085","fireBaseToken":"fVuFWIjEfX0:APA91bHmE4POcCZtzRnROYGAuCEoKrK_Ayv2U9Ptfz3jA4OEEbXOBURsWOf8JWC8ghjrpx2seWmxLcYjUNxnYl0FERt9SiGuE8QwQ-xoZ2m1K9dA8Ii4NdEPTAwbuspF3-YmgSCUmFZg","os":"android"}

**Comment by tuannv19** [comment]
os : chỉ được sử dụng param "android" , không được sử dụng "Android" , "anDroid"...

**Comment by QuyNguyenThu** [comment]
ok

**Comment by QuyNguyenThu** [comment]
@dhhieu113 : 2 requests API trên đã gửi đúng yêu cầu là "android" vẫn báo lỗi. Nhờ API check lại giúp
